// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxwe12VRAJabRQZzeeHo4AEKZeHRy33g',
    appId: '1:464847787225:web:3898f1ceaed6a87f53dac8',
    messagingSenderId: '464847787225',
    projectId: 'connect-me-3d694',
    authDomain: 'connect-me-3d694.firebaseapp.com',
    storageBucket: 'connect-me-3d694.appspot.com',
    measurementId: 'G-VCBHW63N9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4efe8GoGUVn20AjRZgHP_9uZm0OnEUC0',
    appId: '1:464847787225:android:8478077ad75173f453dac8',
    messagingSenderId: '464847787225',
    projectId: 'connect-me-3d694',
    storageBucket: 'connect-me-3d694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9sZKtz4Rf_seB0sHIG_9W3TSu0U9kSw',
    appId: '1:464847787225:ios:0fc525efecfc866953dac8',
    messagingSenderId: '464847787225',
    projectId: 'connect-me-3d694',
    storageBucket: 'connect-me-3d694.appspot.com',
    iosBundleId: 'com.example.connectMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9sZKtz4Rf_seB0sHIG_9W3TSu0U9kSw',
    appId: '1:464847787225:ios:7490dad69b536bd253dac8',
    messagingSenderId: '464847787225',
    projectId: 'connect-me-3d694',
    storageBucket: 'connect-me-3d694.appspot.com',
    iosBundleId: 'com.example.connectMe.RunnerTests',
  );
}
